services:
  reservations:
    build:
      context: .
      dockerfile: apps/reservations/Dockerfile
      target: development
    command: yarn run start:dev reservations
    ports:
      - '3000:3000'
    env_file:
      - ./apps/reservations/.env
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=dev

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn run start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=dev

  mongo:
    image: mongo
